stages:
  - checkFormatting
  - cmakeAndBuild
  - runTests

checkFormatting:
  stage: checkFormatting
  image: fizzyshow/clang-format-alpine
  only:
    - merge_requests
  script:
    - find . -regex '.*\.\(cpp\|c\|h\)' -exec clang-format -style=file --dry-run -Werror -i {} \+

build:
  stage: cmakeAndBuild
  image: fizzyshow/cmake-alpine
  artifacts:
    untracked: true
  only:
    - merge_requests
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target oraap_tests

deploy:
  stage: runTests
  image: fizzyshow/libgcc
  dependencies:
    - build
  only:
    - merge_requests
  script:
    - cd build/test
    - ./oraap_tests --gtest_output="xml:report.xml"
  artifacts:
    when: always
    reports:
      junit: build/test/report.xml
